installCRDs: true
ingressShim:
  defaultIssuerName: "letsencrypt-prod"
  defaultIssuerKind: "ClusterIssuer"
  defaultIssuerGroup: "cert-manager.io"
global:
  leaderElection:
    namespace: "cert-manager"
